apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindx-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 57.158.73.138.nip.io
    secretName: mindx-tls
  rules:
  - host: 57.158.73.138.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mindx-web-service
            port:
              number: 8080